server:
  port: 8082
spring:
  application:
    name: socket-api
  main:
    allow-bean-definition-overriding: true
management:
  endpoints:
    web:
      exposure:
        include: 'prometheus'
  metrics:
    tags:
      application: ${spring.application.name}
  endpoint:
    prometheus:
      enabled: true

python-service:
  host: localhost
  port: 10123